### ISSUE TITLE
Could not find method android.bluetooth.BluetoothAdapter.isOffloadedFilteringSupported

### ISSUE THREAD

**Issue by Lumbi** [reelyactive/ble-android-sdk#1]
Getting this error when using `BluetoothLeScannerCompatProvider.getBluetoothLeScannerCompat()`

Android version: 4.42
minSdkVersion: 18
targetSdkVersion: 23
compile 'com.reelyactive:blesdk:0.5.7@aar'

I'm using the scanner in a `IntentService` so that scanning can be done in background.
`<service android:name=".myawesomeservice" android:exported="false" />`

``` @Override
    protected void onHandleIntent(Intent intent) {
             [...]
             BluetoothLeScannerCompatProvider.getBluetoothLeScannerCompat(getApplicationContext())
             [...]
    }
```

Seems like the `Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP` check didn't work?
Though I logged `Build.VERSION.SDK_INT` in my service and it returned **19** and `Build.VERSION_CODES.LOLLIPOP` returned **21**.

**Comment by saiimons** [comment]
Hi @Lumbi, which kind of error are you getting ?
Can you please copy-paste your logs/stack trace ?

Please try switching to 'com.reelyactive:blesdk:0.6.0@aar', which could fix your issue (I just realized I did not tagged this version until this morning, nor did I update the docs, sorry about this).
If you do, I am still interested in reading the logs from your previous error.

**Comment by Lumbi** [comment]
Updated to 0.6.0, same problem.
The error is  just an error message in the console. There's no stacktrace. 
I used the same API in an `Activity` instead of an `IntentService` and it worked fine. Kinda strange.

Here's the full log:

```
04-01 07:50:41.055 17212-18390/xx.xxx.xxx.xxx I/dalvikvm: Could not find method android.bluetooth.BluetoothAdapter.isOffloadedFilteringSupported, referenced from method com.reelyactive.blesdk.support.ble.BluetoothLeScannerCompatProvider.areHardwareFeaturesSupported
04-01 07:50:41.055 17212-18390/xx.xxx.xxx.xxx W/dalvikvm: VFY: unable to resolve virtual method 237: Landroid/bluetooth/BluetoothAdapter;.isOffloadedFilteringSupported ()Z
04-01 07:50:41.055 17212-18390/xx.xxx.xxx.xxx D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
04-01 07:50:41.075 17212-18390/xx.xxx.xxx.xxx W/BluetoothCrashResolver: Can't read macs from BluetoothCrashResolverState.txt
04-01 07:50:41.095 17212-17212/xx.xxx.xxx.xxx I/BleScanCompatLib: Scan : No clients left, canceling alarm.
```

Also, after subsequent scans, only this part is logged:
`04-01 07:50:54.065 17212-17212/xx.xxx.xxx.xxx I/BleScanCompatLib: Scan : No clients left, canceling alarm.`

**Comment by saiimons** [comment]
So you are running the app on a KitKat and this code is executed ?
Which device is it ?
Can you catch the whole thing on the debugger with a breakpoint in BluetoothLeScannerCompatProvider.areHardwareFeaturesSupported and give me the details ?

I can't recall seeing this message, I need to find a way to reproduce it.
Can you reproduce this issue with the example application provided with the project ?

**Comment by Lumbi** [comment]
**Device**
Model number: SM-G900F
Android version 4.4.2

**Code Here**
http://pastebin.com/2gyZMj9R

I stepped in the SDK's code in the debugger and it didn't take the path calling `areHardwareFeaturesSupported`. It's using the `JbBluetoothLeScannerCompat` scanner. 
It might be that there's no issue with `isOffloadedFilteringSupported` after all. Might just be a warning.

What about this log? What does it mean?
`I/BleScanCompatLib: Scan : No clients left, canceling alarm.`

**Comment by Lumbi** [comment]
OK, I think I found the issue.
I'm using an `IntentService` and the service get's destroyed after starting the scan.
When the `IntentService` gets destroyed the scan callback gets deallocated and the scan stops because there're no more clients.
I should use a plain `Service` instead.

**Comment by saiimons** [comment]
I think the best way for you to handle this would be to use the [ReelyAwareApplicationCallback](https://github.com/reelyactive/ble-android-sdk/blob/master/library/src/main/java/com/reelyactive/blesdk/application/ReelyAwareApplicationCallback.java), and then send your broadcasts.
Though, If your broadcasts aim activities, the best way to handle this part would be using the [ReelyAwareActivity](https://github.com/reelyactive/ble-android-sdk/blob/master/library/src/main/java/com/reelyactive/blesdk/application/ReelyAwareActivity.java).

Have a look at the [tutorial](https://github.com/reelyactive/ble-android-sdk#scan-with-a-simple-api) for more information about the various ways to use the SDK :smile:
